# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('project_description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('time_uloaded', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
